# Generated by Django 4.2.5 on 2023-09-17 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Address')),
                ('mobile_number', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Company Mobile Number')),
                ('website', models.URLField(blank=True, max_length=255, null=True, unique=True, verbose_name='Company Website Link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevicesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('device_id', models.CharField(max_length=255, unique=True, verbose_name='Device Id')),
                ('checked_out', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corporate_assets.companyinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('company_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_inf', to='corporate_assets.companyinfo')),
                ('device_info', models.ManyToManyField(related_name='devices_informations', to='corporate_assets.devicesinfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
